version: 2

sources:
  - name: raw_data
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: raw_data
    tables:
      - name: events
        description: "Raw event logs ingested from CSV"
        columns:
          - name: timestamp
            description: "The time the event occurred"
            tests:
              - not_null
